version: '3'

services:

  mysql1:
    image: mysql:latest
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      
  mysql2:
    image: mysql:latest
    ports:
    - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password